# "$schema" = 'https://starship.rs/config-schema.json' # Get editor completions based on the config schema

add_newline = true # Inserts a blank line between shell prompts

format = """
$python\
$direnv\
$nix_shell\
$username\
$hostname\
$localip\
$directory\
$vcsh\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$docker_context\
$package\
$line_break\
$character"""

[character]
success_symbol = '[➜](bold green) '
error_symbol = '[✗](bold red) '

[package]
disabled = false

[python]
format = '(\($virtualenv\) )'
