# "$schema" = 'https://starship.rs/config-schema.json' # Get editor completions based on the config schema

add_newline = true # Inserts a blank line between shell prompts

format = """
$python\
$direnv\
$nix_shell\
$username\
$hostname\
$localip\
$directory\
$vcsh\
$docker_context\
$fill\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$line_break\
$character"""

[character]
success_symbol = '[➜](bold green) '
error_symbol = '[✗](bold red) '

[fill]
symbol = ' '

[git_branch]
format = '\[[$symbol$branch(:$remote_branch)]($style)\]'
style = 'none'
symbol = " "

[git_commit]
style = 'none'
tag_symbol = '  '

[git_state]
style = 'none'

[git_status]
style = 'none'

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[python]
format = '(\($symbol$virtualenv\) )'
symbol = " "

