#!/bin/sh
SESSION=`basename $1`
echo "Creating tmux session" $SESSION "..."

tmux -2 new-session -d -s $SESSION
tmux rename-window -t $SESSION:1 main
tmux split-window -v
tmux split-window -h
tmux new-window -t $SESSION -a -n git 'lazygit'
tmux select-window -t $SESSION:1
tmux -2 switch -t $SESSION
